name: custom_vimeo_player
description: 'A Flutter package for embedding Vimeo videos with customizable playback controls, events handling.'
version: 1.0.0
homepage: https://github.com/taiseiiiii

environment:
  sdk: ^3.5.4
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
